channels:
  - conda-forge
dependencies:
  - nodejs
  - jupyter_contrib_nbextensions
  - numpy
  - jupyter-server-proxy
  - code-server 
  - nbgitpuller
  - r-base=4
  - r-essentials=4
  - codebraid
  - octave_kernel
  - ruby
