channels:
  - conda-forge
  - coolprop
dependencies:
  - jupyter_contrib_nbextensions
  - rise
  - nbgitpuller
  - r-base
  - r-essentials
  - coolprop
  
  # - pip:
  #   - coolprop

  # - r-tidyverse