channels:
  - conda-forge
dependencies:
  # - coolprop
  - jupyter_contrib_nbextensions
  - nbgitpuller
  - r-base
  - codebraid
  - octave_kernel
  - octave
  
  # - pip
  # - pip:
  #   - jupyter-booktr