#!/bin/sh

# CoolProp.jl
julia -e 'import Pkg && Pkg.add(url = "https://github.com/CoolProp/CoolProp.jl.git")'

# install more r packages. these will be compiled on the spot
R --quiet -f r/install.R

# enable jupyter extensions
jupyter nbextension enable livemdpreview/livemdpreview