#!/bin/sh



# install more r packages. these will be compiled on the spot
R --quiet -f binder/r/install.R

# enable jupyter extensions
jupyter nbextension enable livemdpreview/livemdpreview              
jupyter nbextension enable equation-numbering/main

jupyter labextension install              \
  @deathbeds/jupyterlab-drawio            \
  @deathbeds/jupyterlab-drawio-notebook   \
  @deathbeds/jupyterlab-drawio-webpack    \
  @jupyterlab/mathjax3-extension          \
  @jupyterlab/server-proxy  --minimize=False

# --minimize=False seems to be the key              


# to do 
# ⋅ mathjax extensions

# HOME=/home/jovyan/LabKit.Demos/work
# export HOME
cd ~

